name: CI

on:
  push:
    branches: [ feature/test_ci ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
        
      - name: Setup Environment
        env:
          ADMOB_APPLICATION_ID: ${{ secrets.ADMOB_APPLICATION_ID }}
          ADMOB_HOME_BANNER_ID: ${{ secrets.ADMOB_HOME_BANNER_ID }}
          FAKE_ADMOB_HOME_BANNER_ID: ${{ secrets.FAKE_ADMOB_HOME_BANNER_ID }}
        run: echo "$ADMOB_APPLICATION_ID" > ./secret.properties |
              echo "$ADMOB_HOME_BANNER_ID" > ./secret.properties |
              echo "$FAKE_ADMOB_HOME_BANNER_ID" > ./secret.properties

      - name: Where am I
        run: ls

      - name: Show fake secrets
        run: cat secret.properties
              
      - name: Run all tests
        run: ./gradlew test
