name: CI

on:
  pull_request:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '17'

      - name: Setup Github Packages
        run: |
          echo "//maven.pkg.github.com/JoaoGeniselli/ktransposer:$GITHUB_TOKEN" > $HOME/.gradle/gradle.properties |
          echo "//maven.pkg.github.com/JoaoGeniselli/arpeggio:$GITHUB_TOKEN" > $HOME/.gradle/gradle.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Troque GH_TOKEN pelo nome do seu segredo

      - name: Setup secret.properties
        env:
          ADMOB_APPLICATION_ID: ${{ secrets.ADMOB_APPLICATION_ID }}
          ADMOB_HOME_BANNER_ID: ${{ secrets.ADMOB_HOME_BANNER_ID }}
          ADMOB_TRANSPOSER_BANNER_ID: ${{ secrets.ADMOB_TRANSPOSER_BANNER_ID }}
          FAKE_ADMOB_HOME_BANNER_ID: ${{ secrets.FAKE_ADMOB_HOME_BANNER_ID }}
          GITHUB_PACKAGES_USER: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          echo "ADMOB_APPLICATION_ID=\"$ADMOB_APPLICATION_ID\"" >> ./secret.properties |
          echo "ADMOB_HOME_BANNER_ID=\"$ADMOB_HOME_BANNER_ID\"" >> ./secret.properties |
          echo "ADMOB_TRANSPOSER_BANNER_ID=\"$ADMOB_TRANSPOSER_BANNER_ID\"" >> ./secret.properties |
          echo "GITHUB_PACKAGES_USER=\"$GITHUB_PACKAGES_USER\"" >> ./secret.properties |
          echo "GITHUB_PACKAGES_TOKEN=\"$GITHUB_PACKAGES_TOKEN\"" >> ./secret.properties

      - name: Setup firebase auth
        env:
          FIREBASE_AUTH: ${{ secrets.FIREBASE_AUTH }}
        run: echo "$FIREBASE_AUTH" > ./app/google-services.json

      - name: Run all tests
        run: ./gradlew test
